@@include('files/adaptive.js', {})
@@include('files/functions.js', {})
@@include('files/script.js', {})
@@include('files/forms.js', {})
@@include('files/jq-functions.js', {})
@@include('files/sliders.js', {})